PortfolioWebMVC/Controllers/AcademicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PortfolioWebMVC.Data;
using StefanBrunotteWebPage.Models;

namespace PortfolioWebMVC.Controllers
{
    public class AcademicController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AcademicController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Academic
        public async Task<IActionResult> Index()
        {
           
            return View(await _context.AcademicViewModel.ToListAsync());
        }

        // GET: Academic Search
        public async Task<IActionResult> IndexSearchResult()
        {
            return View(await _context.AcademicViewModel.ToListAsync());
        }

        // GET: Academic/ShowSearchForm
        public IActionResult ShowSearchForm()
        {
            return View();
        }

        // POST: Academic/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("IndexSearchResult", await _context.AcademicViewModel.
                Where(desc=> desc.CourseCoversDescription.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: Academic/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var academicViewModel = await _context.AcademicViewModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (academicViewModel == null)
            {
                return NotFound();
            }

            return View(academicViewModel);
        }

        // GET: Academic/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Academic/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UniversityName,CourseName,CourseCoversDescription,ExperienceGainedDescription,CourseStartDate,CourseEndDate")] AcademicViewModel academicViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(academicViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(academicViewModel);
        }

        // GET: Academic/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var academicViewModel = await _context.AcademicViewModel.FindAsync(id);
            if (academicViewModel == null)
            {
                return NotFound();
            }
            return View(academicViewModel);
        }

        // POST: Academic/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UniversityName,CourseName,CourseCoversDescription,ExperienceGainedDescription,CourseStartDate,CourseEndDate")] AcademicViewModel academicViewModel)
        {
            if (id != academicViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(academicViewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AcademicViewModelExists(academicViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(academicViewModel);
        }

        // GET: Academic/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var academicViewModel = await _context.AcademicViewModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (academicViewModel == null)
            {
                return NotFound();
            }

            return View(academicViewModel);
        }

        // POST: Academic/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var academicViewModel = await _context.AcademicViewModel.FindAsync(id);
            _context.AcademicViewModel.Remove(academicViewModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AcademicViewModelExists(int id)
        {
            return _context.AcademicViewModel.Any(e => e.Id == id);
        }
    }
}

PortfolioWebMVC/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PortfolioWebMVC.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PortfolioWebMVC/Controllers/MeetMeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PortfolioWebMVC.Controllers
{
    public class MeetMeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PortfolioWebMVC/Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PortfolioWebMVC.Data;
using StefanBrunotteWebPage.Models;

namespace PortfolioWebMVC.Controllers
{
    public class WorkController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WorkController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Work
        public async Task<IActionResult> Index()
        {
            return View(await _context.WorkViewModel.ToListAsync());
        }

        // GET: Work Search
        public async Task<IActionResult> IndexSearchResult()
        {
            return View(await _context.WorkViewModel.ToListAsync());
        }

        // GET: Work/ShowSearchForm
        public IActionResult ShowSearchForm()
        {
            return View();
        }

        // POST: Work/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("IndexSearchResult", await _context.WorkViewModel.
                Where(desc => desc.WorkDescription.Contains(SearchPhrase)).ToListAsync());
        }

        // GET: Work/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workViewModel = await _context.WorkViewModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workViewModel == null)
            {
                return NotFound();
            }

            return View(workViewModel);
        }

        // GET: Work/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Work/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CompanyName,WorkDescription,WorkExperienceGainedDescription,WorkStartDate,WorkEndDate")] WorkViewModel workViewModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(workViewModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(workViewModel);
        }

        // GET: Work/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workViewModel = await _context.WorkViewModel.FindAsync(id);
            if (workViewModel == null)
            {
                return NotFound();
            }
            return View(workViewModel);
        }

        // POST: Work/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CompanyName,WorkDescription,WorkExperienceGainedDescription,WorkStartDate,WorkEndDate")] WorkViewModel workViewModel)
        {
            if (id != workViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(workViewModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkViewModelExists(workViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(workViewModel);
        }

        // GET: Work/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workViewModel = await _context.WorkViewModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workViewModel == null)
            {
                return NotFound();
            }

            return View(workViewModel);
        }

        // POST: Work/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workViewModel = await _context.WorkViewModel.FindAsync(id);
            _context.WorkViewModel.Remove(workViewModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkViewModelExists(int id)
        {
            return _context.WorkViewModel.Any(e => e.Id == id);
        }
    }
}

PortfolioWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StefanBrunotte.com</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/e89f599854.js" crossorigin="anonymous"></script>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;0,900;1,400;1,700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&family=Roboto:ital,wght@0,400;0,700;0,900;1,400;1,700&display=swap" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Subrayada:wght@700&display=swap" rel="stylesheet">
    <!-- Favicon -->
    <link rel="icon" href="~/img/favicon_ligth_yellow.ico" sizes="16x16" type="image/png">
    <link rel="stylesheet" href="~/css/site.css" />
    <!-- My Style -->
    <link rel="stylesheet" href="~/css/myStyle.css" />
</head>
<body>
    <img  class="myMediaQueries" src="~/img/anonymousSmall.jpg" alt="" />
    <header class="navArea">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="LandingPage" asp-action="Index">Stefan Brunotte</a>
                <div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1 navLinks">
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="MeetMe" asp-action="Index">Meet Me</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Projects" asp-action="Index">my projects</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Academic" asp-action="Index">My Academics</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Work" asp-action="Index">My Work</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Contact" asp-action="Index">contact me</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-uppercase" href="~/img/pdf/StefanBrunotteCV.pdf" target="blank">my cv</a>
                            </li>
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        &copy; 2021 || Stefan Brunotte || <a href="mailto:mrbrunotte@gmail.com" class="footer-link" target="blank" aria-label="Email: mrbrunotte@gmail.com">contact me</a>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>